- name: playbook for httpd
  hosts: iam1
  tasks:
  - name: installation
    dnf:
      name: httpd
      state: present
  - name: start+enabling process
    service:
      name: httpd
      enabled: yes
      state: started
