- name: playbook for nginx
  hosts: iam1
  tasks:
  - name: installation
    dnf:
      name: nginx >= 1.18.0
      state: present
  - name: start+enabling process
    service:
      name: nginx
      enabled: yes
      state: started
